//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTTData.Com.BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_Products
    {
        public Category_Products()
        {
            this.Product_Line_Items = new HashSet<Product_Line_Items>();
        }
    
        public decimal ProdID { get; set; }
        public decimal CategID { get; set; }
        public string ProdName { get; set; }
        public string ProdDesc { get; set; }
    
        public virtual PS_Categories PS_Categories { get; set; }
        public virtual ICollection<Product_Line_Items> Product_Line_Items { get; set; }
    }
}
