//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTTData.Com.BusinessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetStoreEntities : DbContext
    {
        public PetStoreEntities()
            : base("name=PetStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category_Products> Category_Products { get; set; }
        public virtual DbSet<CreditCard_Info> CreditCard_Info { get; set; }
        public virtual DbSet<Product_Line_Items> Product_Line_Items { get; set; }
        public virtual DbSet<PS_Categories> PS_Categories { get; set; }
        public virtual DbSet<PS_Customer> PS_Customer { get; set; }
        public virtual DbSet<PS_Orders> PS_Orders { get; set; }
        public virtual DbSet<PS_User> PS_User { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
