//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTTData.Com.BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Line_Items
    {
        public decimal ItemID { get; set; }
        public decimal CategID { get; set; }
        public decimal ProdID { get; set; }
        public string ItemName { get; set; }
        public string ItemDesc { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Category_Products Category_Products { get; set; }
        public virtual PS_Categories PS_Categories { get; set; }
    }
}
