//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTTData.Com.BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS_Customer
    {
        public PS_Customer()
        {
            this.PS_Orders = new HashSet<PS_Orders>();
        }
    
        public string CustID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> ContactNo { get; set; }
        public Nullable<decimal> CreditCardNo { get; set; }
    
        public virtual CreditCard_Info CreditCard_Info { get; set; }
        public virtual ICollection<PS_Orders> PS_Orders { get; set; }
        public virtual PS_User PS_User { get; set; }
    }
}
