//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTTData.Com.BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS_Categories
    {
        public PS_Categories()
        {
            this.Category_Products = new HashSet<Category_Products>();
            this.Product_Line_Items = new HashSet<Product_Line_Items>();
        }
    
        public decimal CategID { get; set; }
        public string CategName { get; set; }
        public string CategDesc { get; set; }
    
        public virtual ICollection<Category_Products> Category_Products { get; set; }
        public virtual ICollection<Product_Line_Items> Product_Line_Items { get; set; }
    }
}
