//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard_Info
    {
        public CreditCard_Info()
        {
            this.PS_Customer = new HashSet<PS_Customer>();
        }
    
        public decimal CreditCardNo { get; set; }
        public Nullable<decimal> CardType { get; set; }
        public Nullable<System.DateTime> ExpiryDt { get; set; }
    
        public virtual ICollection<PS_Customer> PS_Customer { get; set; }
    }
}
