//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS_User
    {
        public string CustID { get; set; }
        public string Password { get; set; }
    
        public virtual PS_Customer PS_Customer { get; set; }
    }
}
